#!/bin/bash

if [ "$(systemctl is-active gutendex-books)" = "active" ]
then
    echo "gutendex-books service is $(systemctl is-active gutendex-books), stopping"
    systemctl stop gutendex-books.service
fi

package_dir='/usr/share/gutendex-books/'
python_virtual_env='python_venv'

# create virtual environment and install utilities
echo "Creating python virtual environment"
/usr/bin/python3 -m venv ${package_dir}${python_virtual_env}
echo "Activating python virtual environment"
source ${package_dir}${python_virtual_env}/bin/activate
echo "Installing python dependencies in virtual environment"
pip3 install -r /usr/share/gutendex-books/requirements.txt

# create gutendex-books service file
cat <<EOF > /etc/systemd/system/gutendex-books.service
[Unit]
Description=The Gutendex Books Service
After=network.target

[Service]
ExecStart=${package_dir}${python_virtual_env}/bin/python3 main.py
WorkingDirectory=${package_dir}
StandardOutput=inherit
StandardError=inherit
Restart=on-failure
RestartSec=10
User=root

[Install]
WantedBy=multi-user.target
EOF



# reload and start systemd services
echo "Systemd daemon reload"
systemctl daemon-reload
echo "Enabling gutendex-books service"
systemctl enable gutendex-books.service
echo "Starting gutendex-books service"
systemctl start gutendex-books.service